module.exports = {
  qantas: {
    hasEarn: true,
    hasBurn: true,
    brandName: 'Qantas',
    rewardName: 'Qantas Points',
    programName: 'Qantas frequent flyer',
    prefix: 'qff',
    landingPage: 'qantas-frequent-flyer',
    programLogo: 'QffLogo_2x_i99mv5',
    reverseLogo: 'QffLogoReverse_2x_sxllsy',
    icon: 'Qantas_2x_f6vhzx',
    iconReversed: 'qantas_logo_reversed',
    rewardPer: '$1',
    rewardCurrency: 'AUD',
    color: '#E5242A',
    joinUrl: 'https://www.qantaspoints.com/join-now?code=LUXURYESCAPES',
    numberMaxLength: 14,
    accountFields: ['qff', 'qff_last_name'],
  },
  krisFlyer: {
    hasEarn: true,
    hasBurn: false,
    brandName: 'Singapore Airlines',
    rewardName: 'KrisFlyer Miles',
    programName: 'Kris flyer',
    prefix: 'kfp',
    landingPage: 'kris-flyer',
    programLogo: 'krisFlyerLogo_2x_md61qq',
    reverseLogo: 'krisFlyerLogoReverse_2x_gaivta',
    icon: 'krisFlyer_2x_izuqwc',
    iconReversed: 'krisFlyer_reverse_2x_tabtb2',
    rewardCurrency: 'USD',
    rewardPer: '$1 USD',
    color: '#1D4886',
    numberMaxLength: 10,
    accountFields: ['kfp', 'kfp_first_name', 'kfp_last_name'],
  },
}