module.exports = {
  regions: [
    {
      code: 'AU',
      name: 'Australia',
      lang: 'en-AU',
      currency_formatting_locale: 'en-AU',
      currency_code: 'AUD',
    },
    {
      code: 'CA',
      name: 'Canada',
      lang: 'en-CA',
      currency_formatting_locale: 'en-CA',
      currency_code: 'CAD',
    },
    {
      code: 'FR',
      name: 'France',
      lang: 'en-FR',
      currency_formatting_locale: 'fr-FR',
      currency_code: 'EUR',
    },
    {
      code: 'DE',
      name: 'Germany',
      lang: 'en-DE',
      currency_formatting_locale: 'de-DE',
      currency_code: 'EUR',
    },
    {
      code: 'HK',
      name: 'Hong Kong',
      lang: 'en-HK',
      currency_formatting_locale: 'en-HK',
      currency_code: 'HKD',
    },
    {
      code: 'IN',
      name: 'India',
      lang: 'en-IN',
      currency_formatting_locale: 'en-IN',
      currency_code: 'INR',
    },
    {
      code: 'IE',
      name: 'Ireland',
      lang: 'en-IE',
      currency_formatting_locale: 'en-IE',
      currency_code: 'EUR',
    },
    {
      code: 'IL',
      name: 'Israel',
      lang: 'en-IL',
      currency_formatting_locale: 'iw-IL',
      currency_code: 'ILS',
    },
    {
      code: 'IT',
      name: 'Italy',
      lang: 'en-IT',
      currency_formatting_locale: 'it-IT',
      currency_code: 'EUR',
    },
    {
      code: 'KR',
      name: 'Korea',
      lang: 'en-KR',
      currency_formatting_locale: 'ko-KR',
      currency_code: 'KRW',
    },
    {
      code: 'MY',
      name: 'Malaysia',
      lang: 'en-MY',
      currency_formatting_locale: 'ms-MY',
      currency_code: 'MYR',
    },
    {
      code: 'NZ',
      name: 'New Zealand',
      lang: 'en-NZ',
      currency_formatting_locale: 'en-NZ',
      currency_code: 'NZD',
    },
    {
      code: 'PH',
      name: 'Philippines',
      lang: 'en-PH',
      currency_formatting_locale: 'en-PH',
      currency_code: 'PHP',
    },
    {
      code: 'SG',
      name: 'Singapore',
      lang: 'en-SG',
      currency_formatting_locale: 'en-SG',
      currency_code: 'SGD',
    },
    {
      code: 'ZA',
      name: 'South Africa',
      lang: 'en-ZA',
      currency_formatting_locale: 'af-ZA',
      currency_code: 'ZAR',
    },
    {
      code: 'ES',
      name: 'Spain',
      lang: 'en-ES',
      currency_formatting_locale: 'es-ES',
      currency_code: 'EUR',
    },
    {
      code: 'GB',
      name: 'United Kingdom',
      lang: 'en-GB',
      currency_formatting_locale: 'en-GB',
      currency_code: 'GBP',
    },
    {
      code: 'US',
      name: 'United States',
      lang: 'en-US',
      currency_formatting_locale: 'en-US',
      currency_code: 'USD',
    },
  ],

  defaultRegionCode: 'AU',
}
